version: '3.9'

networks:
  api-network:
    driver: bridge
    
services:
  fastapi-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    
    ports:
      - "8080:8080"

    command: sh -c "fastapi run src/main.py --reload --port=8080"
    networks:
      - api-network

  postgres_db:
    image: postgres:14.12-alpine3.19
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    networks:
      - api-network

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres_db
    ports:
      - "16543:80"
    hostname: "localhost"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - /var/lib/pgadmin/data 
    networks:
      - api-network
